### ISSUE TITLE
使用小狼毫夜间版本不生效

### ISSUE THREAD

**Issue by xiaoyixiao369** [hchunhui/librime-cloud#15]
使用小狼毫夜间版本[https://github.com/rime/weasel/releases/tag/latest](https://github.com/rime/weasel/releases/tag/latest)，无法触发云输入，作者可以看下吗

**Comment by hchunhui** [comment]
原因应该是新的小狼毫开始用64位编译了。我刚对应添加了64位编译，请帮忙测一下 `out-mingw64` 里面的 dll 是否能生效
