### ISSUE TITLE
没有mac版本的？还是和linux一样？

### ISSUE THREAD

**Issue by jimmy54** [hchunhui/librime-cloud#2]
rt

**Comment by hchunhui** [comment]
我没有 mac 环境，所以没法做 mac 版本。
云输入中系统相关的部分是 luasocket，用来让 lua 脚本联网的二进制插件。luasocket 有 mac 下的 Makefile，所以有环境的话编译起来应该比较容易。另外如有办法用其他方法能装上 luasocket 并且配置正确的话应该也能用。

**Comment by jimmy54** [comment]
ok,我研究一下。

**Comment by ctermiii** [comment]
下载本方案，make一次，会自动下载相关文件，报错。
然后进入luasocket目录  make DEBUG=DEBUG PLAT=macosx LUAINC_macosx_base=/tmp/librime-cloud/thirdparty/ LUAV=5.4 LUAPREFIX_macosx=/tmp/lua install
将tmp/lua中文件放入/usr/share对应目录。

然后参照安装说明引入rime.lua即可使用
