### ISSUE TITLE
macOS能使用这个吗

### ISSUE THREAD

**Issue by qq420100523** [hchunhui/librime-cloud#7]

**Comment by flyinguard** [comment]
同问。

**Comment by ctermiii** [comment]
下载本方案，make一次，会自动下载相关文件，报错。
然后进入luasocket目录  make DEBUG=DEBUG PLAT=macosx LUAINC_macosx_base=/tmp/librime-cloud/thirdparty/ LUAV=5.4 LUAPREFIX_macosx=/tmp/lua install
将tmp/lua中文件放入/usr/share对应目录。

然后参照安装说明引入rime.lua即可使用

**Comment by flyinguard** [comment]
> 下载本方案，make一次，会自动下载相关文件，报错。 然后进入luasocket目录 make DEBUG=DEBUG PLAT=macosx LUAINC_macosx_base=/tmp/librime-cloud/thirdparty/ LUAV=5.4 LUAPREFIX_macosx=/tmp/lua install 将tmp/lua中文件放入/usr/share对应目录。
> 
> 然后参照安装说明引入rime.lua即可使用

ctermiii 你好，我按照你的方案执行到第二步，报这样的错误，你看你能给我指点一下么？

/Library/Developer/CommandLineTools/usr/bin/make -C src install
install -d /tmp/lua/share/lua/5.4
install -m644 ltn12.lua socket.lua mime.lua /tmp/lua/share/lua/5.4
install -d /tmp/lua/share/lua/5.4/socket
install -m644 http.lua url.lua tp.lua ftp.lua headers.lua smtp.lua /tmp/lua/share/lua/5.4/socket
install -d /tmp/lua/lib/lua/5.4/socket
install socket-3.0.0.so /tmp/lua/lib/lua/5.4/socket/core.so
install: socket-3.0.0.so: No such file or directory
make[1]: *** [install] Error 71
make: *** [install] Error 2

谢谢了。

**Comment by hchunhui** [comment]
现在可以了

**Comment by qq420100523** [comment]
> 现在可以了

大佬，mac版怎么使用，能否更新一下README

**Comment by hchunhui** [comment]
应该与linux用法类似吧。我不是mac用户，只是研究了一下怎么在CI中编译
