### ISSUE TITLE
使用simplehttp.dll 调用 php 的url 有参的时候返回值为空

### ISSUE THREAD

**Issue by zigeweiwu** [hchunhui/librime-cloud#9]
https://dayu.qqsuu.cn/neihanduanzi/apis.php?type=json

例如上面的接口，在其他的api客户端中调用是可以正常使用 (不能解决也没有关系)

还有就是是不是可以调用斗图网站的api，添加斗图的插件功能

**Comment by hchunhui** [comment]
好像没有复现这个现象。是否是因为网络原因，或者是 `simplehttp.TIMEOUT` 设置过短导致？

**Comment by zigeweiwu** [comment]
> 好像没有复现这个现象。是否是因为网络原因，或者是 `simplehttp.TIMEOUT` 设置过短导致？

是` simplehttp.TIMEOUT` 设置问题，现在设置成5没有问题
